"""
AffordGrasp Configuration
=========================
Central configuration for the AffordGrasp pipeline reproduction.
Covers simulation, VLM reasoning, visual grounding, and grasp generation parameters.

Author: Irbaaz Patel (MSc Robotics & Embedded Systems, Heriot-Watt University)
Reference: Tang et al., "AffordGrasp: In-Context Affordance Reasoning for
           Open-Vocabulary Task-Oriented Grasping in Clutter", IROS 2025
"""

import os
from dataclasses import dataclass, field
from typing import List, Tuple, Optional


@dataclass
class SimulationConfig:
    """PyBullet simulation environment parameters."""
    # Physics
    time_step: float = 1.0 / 240.0
    gravity: Tuple[float, float, float] = (0.0, 0.0, -9.81)

    # ── Robot selection ────────────────────────────────────────────────────────
    # "hsr"   → Toyota HSR (hsrb4s_pybullet.urdf) — dissertation target
    # "panda" → Franka Panda (bundled with pybullet_data) — original baseline
    robot_type: str = "hsr"

    # ── Franka Panda (robot_type="panda") ─────────────────────────────────────
    robot_urdf: str = "franka_panda/panda.urdf"
    end_effector_index: int = 11  # panda_grasptarget link (between fingers)
    # Home joint configuration for Franka Panda (7 arm joints)
    home_joint_positions: Tuple = (0.0, -0.785, 0.0, -2.356, 0.0, 1.571, 0.785)

    # ── Toyota HSR (robot_type="hsr") ─────────────────────────────────────────
    # Path to the PyBullet-compatible URDF (generated by fix_hsr_urdf.py).
    hsr_urdf: str = "hsr_description/robots/hsrb4s_pybullet.urdf"

    # Controllable arm joints in kinematic order (lift → flex → roll → wrist)
    hsr_arm_joints: List[str] = field(default_factory=lambda: [
        "arm_lift_joint",   # prismatic 0–0.69 m  (torso height)
        "arm_flex_joint",   # revolute  -2.62–0   (shoulder pitch)
        "arm_roll_joint",   # revolute  -2.09–3.84 (upper arm roll)
        "wrist_flex_joint", # revolute  -1.92–1.22 (wrist pitch)
        "wrist_roll_joint", # revolute  -1.92–3.67 (wrist roll)
    ])

    # Gripper: hand_motor_joint drives both proximal fingers via mimic joints.
    # PyBullet ignores <mimic>; we sync the fingers manually in code.
    hsr_gripper_joint: str = "hand_motor_joint"    # -0.798–1.24 rad
    hsr_finger_joints: List[str] = field(default_factory=lambda: [
        "hand_l_proximal_joint",
        "hand_r_proximal_joint",
    ])
    hsr_finger_multipliers: List[float] = field(default_factory=lambda: [
        0.5,   # left proximal: same direction, half travel
        0.5,   # right proximal: same direction, half travel
    ])

    # torso_lift_joint mimics arm_lift_joint with multiplier 0.5 in the real
    # robot; PyBullet ignores this — we sync it manually.
    hsr_torso_lift_joint: str = "torso_lift_joint"

    # End-effector and camera links
    hsr_ee_link: str       = "hand_palm_link"       # IK target
    hsr_head_joints: List[str] = field(default_factory=lambda: [
        "head_pan_joint",   # revolute -3.84–1.75 rad
        "head_tilt_joint",  # revolute -1.57–0.52 rad
    ])
    # head_rgbd_sensor_link is the on-robot RGB-D camera (like RealSense on head)
    hsr_head_camera_link: str = "head_rgbd_sensor_link"

    # Home configuration: arm tucked, head looking at table surface
    hsr_home_positions: dict = field(default_factory=lambda: {
        "arm_lift_joint":    0.10,   # slightly raised
        "arm_flex_joint":   -2.00,   # arm bent down
        "arm_roll_joint":    0.00,
        "wrist_flex_joint": -1.50,   # wrist pitched to face forward
        "wrist_roll_joint":  0.00,
        "hand_motor_joint":  0.80,   # gripper open
        "head_pan_joint":    0.00,
        "head_tilt_joint":  -0.40,   # looking slightly down at table
    })

    # ── Shared robot base pose ─────────────────────────────────────────────────
    robot_base_position: Tuple[float, float, float] = (0.0, 0.0, 0.0)
    robot_base_orientation: Tuple[float, float, float, float] = (0.0, 0.0, 0.0, 1.0)

    # ── Gripper (Panda legacy — HSR uses hand_motor_joint above) ──────────────
    gripper_type: str = "robotiq_85"  # or "simple_gripper"
    gripper_open_width: float = 0.085  # metres
    gripper_close_width: float = 0.0
    
    # Workspace / Table
    table_position: Tuple[float, float, float] = (0.5, 0.0, 0.0)
    table_size: Tuple[float, float, float] = (0.6, 0.8, 0.02)
    workspace_bounds: dict = field(default_factory=lambda: {
        "x": (0.25, 0.75),
        "y": (-0.3, 0.3),
        "z": (0.02, 0.30),
    })
    
    # Camera (eye-to-hand, matching paper's RealSense L515 setup)
    camera_position: Tuple[float, float, float] = (0.5, 0.0, 1.2)
    camera_target: Tuple[float, float, float] = (0.5, 0.0, 0.0)
    camera_up_vector: Tuple[float, float, float] = (0.0, 1.0, 0.0)
    image_width: int = 640
    image_height: int = 480
    camera_fov: float = 60.0
    camera_near: float = 0.01
    camera_far: float = 5.0  # extended for wider depth range

    # Additional camera views for multi-view grounding.
    # Each entry: (name, eye_pos, target_pos, up_vector)
    # Positions chosen to avoid the robot arm (base at origin, arm along +Z/+X).
    # The primary top-down view is always included automatically.
    extra_camera_views: List[Tuple] = field(default_factory=lambda: [
        ("front", (0.08, -0.70, 0.50), (0.50, 0.0, 0.06), (0, 0, 1)),
        ("side",  (1.15,  0.25, 0.50), (0.50, 0.0, 0.06), (0, 0, 1)),
    ])
    
    # Object loading: use YCB meshes from the cloned elpis-lab/YCB_Dataset repo.
    # ycb_data_path is the path to the YCB_Dataset/ycb/ directory that contains
    # the per-object sub-folders (mug/, bowl/, ...) and their matching .urdf files.
    # Set to "" to let PipelineConfig.__post_init__ auto-resolve it relative to
    # this file's location (YCB_Dataset/ycb/ sibling of config.py).
    use_ycb_objects: bool = True
    ycb_data_path: str = ""  # resolved in PipelineConfig.__post_init__

    # Mapping from pipeline category names to elpis-lab/YCB_Dataset folder names.
    # Each value must match a <name>.urdf file in ycb_data_path and a <name>/
    # sub-folder containing textured.obj + texture_map.png + textured_coacd_*.stl.
    category_to_ycb_id: dict = field(default_factory=lambda: {
        "mug":         "mug",
        "cup":         "a_cups",
        "bowl":        "bowl",
        "spoon":       "spoon",
        "hammer":      "hammer",
        "knife":       "knife",
        "fork":        "fork",
        "scissors":    "scissors",
        "screwdriver": "phillips_screwdriver",
        "spatula":     "spatula",
        "bottle":      "mustard_bottle",
        "wine_glass":  "pitcher_base",
        "drill":       "power_drill",
        "kettle":      "tomato_soup_can",
        "racket":      "foam_brick",
        "pan":         "skillet_lid",
    })

    # Clutter settings — only categories that have a YCB mapping are included.
    num_distractor_objects: int = 5
    object_categories: List[str] = field(default_factory=lambda: [
        "mug", "cup", "bowl", "spoon", "hammer",
        "knife", "fork", "scissors", "screwdriver", "spatula",
        "bottle", "wine_glass", "drill", "kettle", "pan",
    ])


@dataclass
class VLMConfig:
    """Vision-Language Model configuration for affordance reasoning."""
    model_name: str = "gpt-4o-2024-08-06"  # supports Structured Outputs
    api_key: str = ""  # Set via environment variable OPENAI_API_KEY
    max_tokens: int = 512
    temperature: float = 0.0  # deterministic per-instruction reasoning -- see
    # affordance_reasoning.py's docstring note on why this matters for
    # part/constraint selection specifically (no response caching exists in
    # this codebase; determinism here comes only from temperature=0)
    
    # Structured Outputs — uses Pydantic models for guaranteed JSON schema
    use_structured_outputs: bool = True
    
    # Robust consensus querying — query VLM n times, take majority vote
    n_consensus_samples: int = 3
    
    # Image detail level: "high" (~850 tokens, better accuracy) or
    # "low" (85 tokens, ~$0.001/call vs ~$0.004/call)
    image_detail: str = "high"
    
    # Prompt templates for three-step reasoning
    system_prompt: str = """You are an expert robotic manipulation assistant. 
You help robots understand how to grasp objects for specific tasks by reasoning 
about object affordances. You analyze scenes and determine which object to grasp 
and which part of that object is optimal for the given task.

Always respond in the exact JSON format requested."""
    
    step1_task_analysis_template: str = """Analyze the following user instruction and extract:
1. The implicit task goal
2. The functional requirements for completing this task
3. The type of tool/object needed

User instruction: "{instruction}"

Respond in JSON format:
{{
    "task_goal": "<what the user wants to accomplish>",
    "functional_requirements": ["<requirement1>", "<requirement2>", ...],
    "required_object_type": "<type of object needed>",
    "required_properties": ["<property1>", "<property2>", ...]
}}"""
    
    step2_object_identification_template: str = """Given the following scene image and task analysis, 
identify the most suitable object for the task.

Task Analysis:
- Task Goal: {task_goal}
- Functional Requirements: {functional_requirements}
- Required Object Type: {required_object_type}

Look at the scene image and identify the best object for this task.

Respond in JSON format:
{{
    "target_object": "<name of the identified object>",
    "object_description": "<brief description of why this object is suitable>",
    "confidence": <0.0-1.0>,
    "approximate_location": "<description of where in the image>"
}}"""
    
    step3_affordance_reasoning_template: str = """You are deciding which part of an object a robot gripper should grasp to accomplish a task. Choose the part a person would most naturally grasp FOR THIS SPECIFIC TASK -- different tasks on the same object often warrant different parts. Do not default to the same part across tasks just because it was right for a different instruction on the same object.

Before naming a part, reason step by step about the constraints the task implies: what surface or region of the object must remain functional/unobstructed during and after the grasp (keep_clear), what happens to the object right after it is picked up (post_grasp_motion), how much the grasp needs to resist slipping or tipping (stability_priority), and whether the object's temperature or cleanliness rules out certain contact points (thermal_or_hygiene).

keep_clear is a STRICT list: include a surface ONLY if obstructing it would physically prevent the task from working. It is not a list of surfaces that would merely be inconvenient or unrelated to touch. For a plain relocation, carrying, or handover task where no surface's function is disrupted by the grasp, the correct and expected answer is an EMPTY keep_clear -- do not populate it out of general caution. Every entry in keep_clear must have a matching one-line entry in keep_clear_reasons (same order, same length) stating the concrete mechanical reason obstructing that surface would break the task; if you cannot state one, leave both lists empty.

One worked example of this reasoning (illustrates the PRINCIPLE only, not the answer -- reason freshly for the actual task below, and do not pattern-match this example onto unrelated tasks): for a pouring task, ask "which surface, if covered by the gripper, would physically stop the liquid from leaving the container?" The opening/rim is the surface the liquid must pass through -- covering it blocks the pour, so it belongs in keep_clear with a reason like "covering this would block the liquid's exit path." Most tasks have no surface that fails this test. When nothing you would touch mechanically blocks the task, keep_clear must be empty -- this is the common case, not the exception.

Instruction: "{instruction}"
Target Object: {target_object}
Task Goal: {task_goal}
Functional Requirements: {functional_requirements}

Respond in strict JSON, no other text:
{{
    "target_object": "<the object you are reasoning about, should match the target object above>",
    "target_part": "<name of the single best part/region to grasp for THIS task>",
    "constraints": {{
        "keep_clear": ["<surface name whose obstruction would physically prevent the task -- empty list if none>"],
        "keep_clear_reasons": ["<one-line mechanical justification for the matching keep_clear entry -- same order and length as keep_clear>"],
        "post_grasp_motion": "<one of: translate, tilt_pour, handover, none>",
        "stability_priority": "<one of: low, med, high>",
        "thermal_or_hygiene": "<a short string describing a thermal or hygiene hazard, or null if none applies>"
    }},
    "rationale": "<brief explanation of why this part and these constraints follow from THIS specific task>",
    "confidence": <0.0-1.0>
}}"""


@dataclass
class VisualGroundingConfig:
    """LangSAM visual grounding module configuration (v0.2.x API)."""
    # LangSAM model variant — sam2.1 variants: "sam2.1_hiera_tiny" (4GB),
    # "sam2.1_hiera_small" (default, ~6GB), "sam2.1_hiera_large" (~10GB)
    sam_variant: str = "sam2.1_hiera_small"
    
    # GroundingDINO detection thresholds
    box_threshold: float = 0.20
    text_threshold: float = 0.20
    
    # Two-pass grounding: crop padding around detected object bbox (pixels)
    crop_padding: int = 20
    
    # Segmentation refinement
    min_mask_area: int = 100  # minimum pixel area for valid mask
    
    # Image processing — paper uses 224x224 for affordance segmentation,
    # but LangSAM works best at native resolution (no resize needed)
    resize_for_segmentation: bool = False

    # Device
    device: str = "cuda"  # or "cpu"

    # Set True to allow simulation segmentation fallback when LangSAM is
    # unavailable. Default False: missing LangSAM raises ImportError so
    # the user knows real perception is not active.
    force_sim_fallback: bool = False

    # Crop the RGB image to this pixel region before passing to LangSAM.
    # Excludes the robot arm (visible on the left edge in the top-down camera view).
    # Format: (x1, y1, x2, y2). Set to None to use the full image.
    # Calibrated for the default camera (0.5, 0, 1.2) → (0.5, 0, 0), 640×480, FOV 60°.
    workspace_image_crop: Optional[Tuple[int, int, int, int]] = (195, 75, 460, 415)


@dataclass
class GraspConfig:
    """Grasp generation configuration."""
    # Method: "contact_graspnet" (recommended open-source) or "antipodal" (fallback)
    method: str = "contact_graspnet"
    
    # Contact-GraspNet configuration (PyTorch port by elchun).
    # Points to the directory that contains config.yaml and a checkpoints/
    # sub-folder with model.pt. The repo clone already ships config.yaml here;
    # download model.pt from the elchun/contact_graspnet_pytorch README and
    # place it at: <cgn_checkpoint_dir>/checkpoints/model.pt
    cgn_checkpoint_dir: str = "third_party/contact_graspnet_pytorch/checkpoints/contact_graspnet"
    cgn_forward_passes: int = 2   # stochastic forward passes (increase for better coverage at higher VRAM cost)
    cgn_z_range: Tuple[float, float] = (0.2, 1.8)  # depth range filter (metres)
    cgn_local_regions: bool = True  # per-segment grasp generation
    cgn_filter_grasps: bool = False  # CGN's internal collision filter rejects all grasps when objects are near table; AffordGrasp ranking handles selection
    
    # Antipodal sampling fallback parameters
    num_grasp_samples: int = 200
    friction_coefficient: float = 0.5
    grasp_width_range: Tuple[float, float] = (0.02, 0.085)
    grasp_depth: float = 0.02
    approach_angle_range: Tuple[float, float] = (-30.0, 30.0)  # degrees from vertical
    num_approach_angles: int = 12
    
    # Affordance-guided ranking — the paper's core formula:
    #   ranking = grasp_score / distance_to_affordance_centre
    # This replaces the weighted-sum approach with the actual AffordGrasp formula.
    min_distance_epsilon: float = 1e-6  # avoids division by zero
    max_distance_from_affordance_center: float = 0.20  # metres, hard cutoff
    
    # Post-processing
    collision_check: bool = True
    top_k_grasps: int = 5

    # Reachability filtering -- drop CGN candidates the arm cannot reach.
    enable_reachability_filter: bool = True
    reachability_residual_threshold: float = 0.03   # 3 cm position tolerance
    reachability_orientation_tolerance_rad: float = 0.524  # ~30 degrees
    min_reachable_candidates: int = 5  # below this, fall back to next tier


@dataclass
class PipelineConfig:
    """Master configuration combining all sub-configs."""
    simulation: SimulationConfig = field(default_factory=SimulationConfig)
    vlm: VLMConfig = field(default_factory=VLMConfig)
    visual_grounding: VisualGroundingConfig = field(default_factory=VisualGroundingConfig)
    grasp: GraspConfig = field(default_factory=GraspConfig)
    
    # Output / logging
    output_dir: str = "results"
    save_visualizations: bool = True
    verbose: bool = True
    
    # Experiment
    experiment_name: str = "affordgrasp_reproduction"
    seed: int = 42

    def __post_init__(self):
        os.makedirs(self.output_dir, exist_ok=True)
        if not self.vlm.api_key:
            self.vlm.api_key = os.environ.get("OPENAI_API_KEY", "")
        # Auto-resolve ycb_data_path relative to this file's location
        if not self.simulation.ycb_data_path:
            from intent_grasp.paths import THIRD_PARTY
            self.simulation.ycb_data_path = str(THIRD_PARTY / "YCB_Dataset" / "ycb")